### ISSUE TITLE
Depend on Embers UEL

### ISSUE THREAD

**Issue by MasterEnderman** [ClassixX/Embersified#2]
Thanks for opening issues.
After looking through your changes, I need to tweak some things on my end to make embers uel compatible with your fork. Mainly disabling the default versions of blocks you add by yourself, as you can no longer overwrite registration by yourself, furthermore you may want to integrate the new config entries I added to most of the machines.

I'm aware that this may break compatibility with the default embers rekindled. If that's a problem for you I may just add some mixins to integrate them myself. I'm open to discussion. :)

**Comment by ClassixX** [comment]
I'm afraid I'll have to insist on compatibility with Rekindled on my end, since the whole intent of this project was to be able to add it to some modpacks that include Rekindled. Feel free to integrate anything you want on your end.

**Comment by MasterEnderman** [comment]
Alright could you at least change the "required dependency" state for embers rekindled to "optional dependency"? that way it won't always try to install embers rekindled if someone want's to use my fork. :) And while at it add my fork as an "optional dependency" as well?

**Comment by ClassixX** [comment]
Of course, no problem
